CREATE TABLE artists (
    artist_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name varchar NOT NULL UNIQUE,
    birthday date NOT NULL,
    birthplace varchar NOT NULL,
    is_alive boolean NOT NULL DEFAULT true
);